spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8889
var:
  filter:
    excluded-paths: /api/auth/login,/api/auth/register,/users/public/images
