apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: application
data:
  spring.profiles.active: "prod"
  application.yml: |
    server:
      port: 8080
    spring:
      application:
        name: gateway-service
    eureka:
      client:
        registerWithEureka: true
        fetchRegistry: true