apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
  namespace: fintech
data:
  application.yml: |-
    spring:
      application:
        name: gateway-service
      cloud:
        gateway:
          routes:
            - id: user-service
              uri: http://user-service:8090
              predicates:
                - Path=/api/users/**
            
            - id: wallet-service
              uri: http://wallet-service:8099
              predicates:
                - Path=/api/wallets/**,/api/currencies/**
            
            - id: notification-service
              uri: http://notification-service:8085
              predicates:
                - Path=/api/notification/**
            
            - id: auth-service
              uri: http://auth-service:8946
              predicates:
                - Path=/api/auth/**
            
            - id: transaction-service
              uri: http://transaction-service:8599
              predicates:
                - Path=/api/transaction/**
      
      config:
        import: optional:configserver:http://config-service:8889
    
    server:
      port: 8222
    
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
    
    var:
      filter:
        excluded-paths: /api/auth/login,/api/auth/register,/users/public/images