apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
  namespace: fintech
data:
  application.yml: |-
    server:
      port: 8222

    spring:
      application:
        name: gateway-service
      cloud:
        gateway:
          routes:
            - id: user-service
              uri: http://user-service:8090
              predicates:
                - Path=/api/users/**

            - id: image-service
              uri: http://user-service:8090
              predicates:
                - Path=/users/public/images/**

            - id: wallet-service
              uri: http://wallet-service:8099
              predicates:
                - Path=/api/wallets/**

            - id: wallet-service-currency
              uri: http://wallet-service:8099
              predicates:
                - Path=/api/currencies/**

            - id: auth-service
              uri: http://auth-service:8946
              predicates:
                - Path=/api/auth/**

            - id: transaction-service
              uri: http://transaction-service:8599
              predicates:
                - Path=/api/transaction/**

    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
      security:
        enabled: false