apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service-config
  namespace: fintech
data:
  application.yml: |-
    spring:
      application:
        name: gateway-service
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: http://user-service.fintech.svc.cluster.local
              predicates:
                - Path=/api/users/**
            - id: wallet-service
              uri: http://wallet-service.fintech.svc.cluster.local
              predicates:
                - Path=/api/wallets/**
            - id: auth-service
              uri: http://auth-service.fintech.svc.cluster.local
              predicates:
                - Path=/api/auth/**
      config:
        import: optional:configserver:http://config-server.fintech.svc.cluster.local:8889

    eureka:
      client:
        serviceUrl:
          defaultZone: http://discovery-service.fintech.svc.cluster.local:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true

    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always