apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: application
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: gateway-service